# Generated by Django 4.1.7 on 2023-04-28 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_postblog_alter_comentario_usuario_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='fechaPost',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postblog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
